### ISSUE TITLE
HCI questions and questionaire

### ISSUE THREAD

**Issue by Codrin-Popa** [CosyClub/ProjectTempo#136]
Come up with a questionnaire for the people that try our game. This will be very useful for ticking the HCI boxes.

Something along the lines:

-> How easy was it to determine what you have to do?
-> Were the instructions clear?
-> On a scale from 1 to 10 how easy was to stay on the beat?
-> On a scale from 1 to 10 how enjoyable have you found the game experience?
-> How involved was the multiplayer experience?
Options: Single-player, Little Multi-player interaction, Clear Multi-player elements 
-> Would you play this game again?
-> What would you improve about the game?

Then the results from this questions can be correlated to questions related to the person's background.
-> For how many years have you been playing video games?
-> On average, how many hours do you spend per week playing video games?
-> Do you prefer Single-player games or Multi-player games?
-> What is your favourite type of computer game?

**Comment by jnterry** [comment]
I'm unable to find much information about the testing day.

I think we need to consider:
- How old are the children?
- How many children are we likely to get through at once? Are we going to get multiple groups of 5 or so, or a single massive batch?

@grant-m-s Do you have any extra details about this?

---------------------------------

We also need to decide how to collect the responses - I would suggest google forms on the PC at which they have played.

---------------------------------

If we get multiple batches of testers coming through I would consider changing the size of the window in which key presses are acceptable and then correlating that with responses. EG, if we had three different window sizes and then correlated that against a reported score out of 10 about how easy it was to hit keys on the beat.

@RcColes @AnthonyWharton You too are probably best to ask about changing the beat window since it ties into networking

**Comment by grant-m-s** [comment]
#124 Related, equally important.

**Comment by Codrin-Popa** [comment]
I've made a Google form for the questionnaire and added it to the shared google drive. We could print it as well.

https://docs.google.com/forms/d/e/1FAIpQLSdahwApyLXMI-rbqgFkEtVId-L-lEQuSc8gWqDhO9aC366PIw/viewform

Any feedback? I will ask Aisling for some feedback as well.

**Comment by grant-m-s** [comment]
I think the answers for "how involved was the ..." need to be changed.
Do we really need to know their favourite genre of game?

**Comment by qqii** [comment]
This was dropped in favour of #157 and taking notes. Nodes are yet to be written up @AnthonyWharton.
